name: Build Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk ifuse libimobiledevice-utils fuse
        
    - name: Build simple package
      run: |
        chmod +x ./build_simple_package.sh
        ./build_simple_package.sh
        
    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: plugnpass-package
        path: plugnpass-*.tar.gz
    
    - name: Upload to release
      if: github.event_name == 'release'
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./plugnpass-*.tar.gz 