name: Build Package

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper dh-python python3-tk ifuse libimobiledevice-utils fuse
        
    - name: Build deb package
      run: |
        chmod +x ./build_deb.sh
        CI=true ./build_deb.sh
        # For GitHub release tagging
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          TAG_NAME="${{ github.ref_name }}"
          cp ../plugnpass_*.deb ./plugnpass_${TAG_NAME#v}_all.deb
        fi
        
    - name: Build simple package
      run: |
        chmod +x ./build_simple_package.sh
        ./build_simple_package.sh
        
    - name: Upload package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: plugnpass-packages
        path: |
          ./plugnpass-*.tar.gz
          ../plugnpass_*.deb
    
    - name: Upload to release
      if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          plugnpass-*.tar.gz
          ../plugnpass_*.deb
          plugnpass_*_all.deb
        draft: false
        generate_release_notes: true
        token: ${{ secrets.GITHUB_TOKEN }} 