name: Build Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper dh-python python3-all python3-setuptools libimobiledevice-utils ifuse fuse
        
    - name: Build package
      run: |
        dpkg-buildpackage -us -uc -b
        
    - name: Upload .deb artifact
      uses: actions/upload-artifact@v3
      with:
        name: plugnpass-deb
        path: ../plugnpass_*.deb
    
    - name: Test installation
      run: |
        sudo apt-get install -y ../plugnpass_*.deb
        plugnpass --version || true 